name: Auto Merge Pull Requests

on:
  pull_request:
    types: [opened, reopened, synchronize]
  status:  # Trigger on status changes (e.g., when CI tests pass)
    branches: [main]
  pull_request_review:  # Trigger on review events (e.g., when a PR gets an approval)
    types: [submitted]

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install black

      - name: Run tests
        run: pytest

      - name: Run black (code formatting check)
        run: black --check .

      - name: Auto Merge PR
        uses: pascalgn/automerge-action@v0.15.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          merge_method: squash  # Can be 'merge', 'rebase', or 'squash'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub provides this token automatically
